# encoding: UTF-8

control 'V-213982' do
  title "SQL Server must provide centralized configuration of the content to be
captured in audit records generated by all components of SQL Server."
  desc  "If the configuration of SQL Server's auditing is spread across
multiple locations in the database management software, or across multiple
commands, only loosely related, it is harder to use and takes longer to
reconfigure in response to events.

    SQL Server must provide a unified tool for audit configuration.
  "
  desc  'rationale', ''
  desc  'check', "
    Review the system documentation for a description of how audit records are
off-loaded and how local audit log space is managed.

    If the SQL Server audit records (to include traces used for audit purposes)
are not written directly to or systematically transferred to a centralized log
management system, this is a finding.
  "
  desc  'fix', "Configure and/or deploy software tools to ensure that SQL
Server audit records (to include traces used for audit purposes) are written
directly to or systematically transferred to a centralized log management
system."
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000356-DB-000315'
  tag gid: 'V-213982'
  tag rid: 'SV-213982r508026_rule'
  tag stig_id: 'SQL6-D0-010800'
  tag fix_id: 'F-15197r313730_fix'
  tag cci: ['V-79225', 'SV-93931', 'CCI-001844']
  tag nist: ['AU-3 (2)']
end

